- name: Get connection credentials from vars
  set_fact:
    vsphere_user: "{{ lookup('env', 'VSPHERE_USER') }}"
    vsphere_hostname: "{{ lookup('env', 'VSPHERE_HOSTNAME') }}"
    vsphere_password: "{{ lookup('env', 'VSPHERE_PASSWORD') }}"

- name: Assert connection credentials are available
  assert:
      that:
        - vsphere_user is defined and vsphere_user | length > 0
        - vsphere_hostname is defined and vsphere_hostname | length > 0
        - vsphere_password is defined and vsphere_password | length > 0