---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
##### UBUNTU
  - name: ubuntu2204-1
    template_name: ubuntu-22-04
    networks:
      - network-1

  - name: ubuntu2204-2
    template_name: ubuntu-22-04
    networks:
      - network-2

  - name: ubuntu2204-3
    template_name: ubuntu-22-04
    networks:
      - network-1
      - network-2
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
    destroy: ../default/destroy.yml
verifier:
  name: ansible
