---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
##### UBUNTU
  - name: ubuntu2204
    template_name: ubuntu-22-04

  - name: ubuntu2004
    template_name: ubuntu-20-04

  - name: ubuntu1804
    template_name: ubuntu-18-04
##### CENTOS
  - name: centos7
    template_name: centos-7

  - name: centos8
    template_name: centos-stream-8

  - name: centos9
    template_name: centos-stream-9
provisioner:
  name: ansible
verifier:
  name: ansible
